version: '3'

services:
  elaastic-questions-db-8: # Elaastic database (except for instructional materials produced by the writer)
    image: mysql:8.3
    container_name: elaastic-questions-db-8
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6683:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  elaastic-writer-db-8: # Writer database (store instructional materials)
      image: mysql:8.3
      container_name: elaastic-questions-writer-8
      environment:
          - MYSQL_USER=elaastic
          - MYSQL_DATABASE=elaastic-writer
          - MYSQL_PASSWORD=elaastic
          - MYSQL_ROOT_PASSWORD=root
      ports:
          - "6783:3306"
      command: --character-set-server=utf8 --collation-server=utf8_general_ci
  elaastic-questions-db-test-8: # Elaastic test database
    image: mysql:8.3
    container_name: elaastic-questions-db-test-8
    environment:
      - MYSQL_USER=elaastic
      - MYSQL_DATABASE=elaastic-questions-test
      - MYSQL_PASSWORD=elaastic
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "6684:3306"
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
  cas:
    container_name: elaastic-cas
    build: docker-resources/cas
    ports:
      - "8443:8443"
  cas-2:
    container_name: elaastic-cas-2
    build: docker-resources/cas
    ports:
      - "8444:8443"
